local:
	REG_OUT=out.ics VIP_OUT=vip_out.ics KVK_OUT=kvk.ics ./build.sh

s3:
	REG_OUT=s3://vikes-misc.irdn.is/leikir_2019.ics VIP_OUT=s3://vikes-misc.irdn.is/leikir_2019_vip.ics KVK_OUT=s3://vikes-misc.irdn.is/leikir_kvk_2019.ics ./build.sh
