local:
	python create_ical.py 2018.xlsx out.ics --name="Pepsideildin 2018 - Víkingur"

s3:
	python create_ical.py 2018.xlsx s3://vikes-misc.irdn.is/leikir_2018.ics --name="Pepsideildin 2018 - Víkingur"