local:
	REG_OUT=out.ics VIP_OUT=vip_out.ics KVK_OUT=kvk.ics ./build.sh

s3:
	REG_OUT=s3://vikes-misc.irdn.is/leikir_2018.ics VIP_OUT=s3://vikes-misc.irdn.is/leikir_2018_vip.ics KVK_OUT=s3://vikes-misc.irdn.is/leikir_kvk_2018.ics ./build.sh
